baseurl = "https://blog.yutaron.tokyo"
languageCode = "ja"
title = "ざっと書くところ"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/yuta-ron\">yuta-ron</a> 2023"
googleAnalytics = "G-3WTS215HYN"
pagination.pagerSize = 20
enableRobotsTXT = true

[params.rss] # Adding this tag enables RSS feed
includeContent = true # Includes whole content in rss
authorName = "Yutaro Nishi" # Author full name
authorEmail = "jan.joqr@gmail.com" # Author email

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article
codeCopy = true # Add copy button above code blocks
taxonomiesCount = true # Add taxonomies count


[params.social]
github = "yuta-ron"
linkedin = "yutaro-nishi-b74090170"
facebook = "100028405416669"
instagram = ""
codepen = ""
rss = "index.xml" # Add this to show RSS button in social.

[params.social.config]
platforms = ["github","facebook","linkedin"]

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true